module AndroidXml

  class XmlFile < Tag

    attr :filename

    def initialize(filename, &block)
      @filename = filename
      super(nil, &block)
      AndroidXml.files << self
    end

    def method_missing(method_name, *args, &block)
      raise "There can be only one (new: #{method_name}, old: #{@root})" if @root

      @root = super
      @root.is_root = true
      @root
    end

    def generate
      output = "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n"
      output << "<!-- Do not edit this file. It was generated by AndroidXml -->\n"
      output << generate_block
    end

    def out
      puts "---- filename: #{@filename} ----"
      super
      puts "---------------#{'-' * @filename.to_s.length}-----"
    end

    def write
      File.open(self.filename, 'w') do |f|
        f.write(self.to_s)
      end
      puts "\033[32m✓\033[0m #{self.filename}"
    end

  end

end
